
name: Docker Image CI for GHCR

on:
  push:
    branches: [main]
    paths-ignore:
      - "README.md"
  pull_request:
    branches: [main]
    paths-ignore:
      - "README.md"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: true
          outputs: type=image,name=target,annotation-index.org.opencontainers.image.description=spotdl-playlist image
          tags: |
<<<<<<< HEAD
            ghcr.io/${{ github.repository }}:latest  
=======
            ghcr.io/${{ github.repository }}:latest  

>>>>>>> e89b0d1919e6eabf0d6a4e3348dbc443c4eff51e